import { PROJECTURL, PUBLIC_ANON_KEY } from './credentials.js';
const supabase = window.supabase.createClient(PROJECTURL, PUBLIC_ANON_KEY);


// create table public.todos (
//   id BIGINT generated by default as identity primary key,
//   todo_name TEXT
// );

// insert
// from
// update
// delete



const addBtn = document.getElementById('add-btn');
const todoInput = document.getElementById('todo');
const todoList = document.getElementById('list');
var updateId = null;

async function fetchTodos() {
    todoList.innerHTML = '';

    const { data, error } = await supabase
        .from('todos')
        .select("*");

    for (let i = 0; i < data.length; i++) {
        const id = data[i].id;
        const name = data[i].todo_name;
        todoList.innerHTML += `<div class="task completed" data-id="${id}">
            <div class="left">
                <span>${name}</span>
            </div>
            <div class="buttons">
                <button onclick="updateTodo(${id}, '${name}')" class="update">Update</button>
                <button class="delete" onclick="deleteTodo(${id})">Delete</button>
            </div>

        </div>`
    }
}


fetchTodos();


async function addTodo() {
    const todoText = todoInput.value;
    if (updateId) {
        const response = await supabase
            .from('todos')
            .update({ todo_name: todoText })
            .eq('id', updateId)
        todoInput.value = '';
        addBtn.innerHTML = 'Add Todo';
        updateId = null;
        fetchTodos()
    } else {
        const record = await supabase
            .from('todos')
            .insert({ todo_name: todoText })

        todoInput.value = '';
        fetchTodos()
    }
}

async function deleteTodo(id) {
    const response = await supabase
        .from('todos')
        .delete()
        .eq('id', id)
    fetchTodos()
}

async function updateTodo(id, name) {
    todoInput.value = name;
    addBtn.innerHTML = 'Update Todo';
    updateId = id;
}


window.deleteTodo = deleteTodo;
window.updateTodo = updateTodo;

addBtn.addEventListener('click', addTodo);    